### ISSUE TITLE
'pyinstaller' is not recognized as an internal command or external

### ISSUE THREAD

**Issue by Ryan4794** [schwungvoll/Hazard-Token-Grabber-v3#2]
![image](https://user-images.githubusercontent.com/110686855/196422440-1c054e5c-7f3d-4b0b-8758-46bc2c45acfd.png)
C:\Users\dehme\Desktop\Hazard-Token-Grabber-v3-main>pyinstaller hazard-v3.py --onefile
'pyinstaller' is not recognized as an internal command
or external, an executable program or a batch file.

everything works except that the 'tutorial' to compile an exe does not work for me

**Comment by schwungvoll** [comment]
Hmm that's really weird, you have instaleld python right? if not, do it on https://www.python.org/downloads/release/python-3108/

**Comment by schwungvoll** [comment]
If that doesn't work I don't have any ideas. When I enter my pc later I will try to code a builder and an auto-install python process. I will also check if I can find another fix or anything about that.
Sorry that it's not working perfectly at the moment..

**Comment by schwungvoll** [comment]
I have another idea, you can try this command:
python hazard-v3.py --onefile

**Comment by schwungvoll** [comment]
@Ryan4794 Have you installed all the requirements through this command?

pip install -r requirements.txt

**Comment by schwungvoll** [comment]
If you didn't follow all the steps exactly, I can't help you.

**Comment by zappelig** [comment]
Heyy..

If you are still interested try "python -m pip install -r requirements.txt"

Also to all the others that have the same problem.

**Comment by Gumbobrot** [comment]
@Ryan4794 i created a builder try the latest vers

**Comment by rubb3rr** [comment]
> ![image](https://user-images.githubusercontent.com/110686855/196422440-1c054e5c-7f3d-4b0b-8758-46bc2c45acfd.png) C:\Users\dehme\Desktop\Hazard-Token-Grabber-v3-main>pyinstaller hazard-v3.py --onefile 'pyinstaller' is not recognized as an internal command or external, an executable program or a batch file.
> 
> everything works except that the 'tutorial' to compile an exe does not work for me

You need to install pyinstaller using pip. Try <pip3 install pyinstaller>

**Comment by rubb3rr** [comment]
> ![image](https://user-images.githubusercontent.com/110686855/196422440-1c054e5c-7f3d-4b0b-8758-46bc2c45acfd.png) C:\Users\dehme\Desktop\Hazard-Token-Grabber-v3-main>pyinstaller hazard-v3.py --onefile 'pyinstaller' is not recognized as an internal command or external, an executable program or a batch file.
> 
> everything works except that the 'tutorial' to compile an exe does not work for me

You need to install pyinstaller using pip. Try "pip3 install pyinstaller"

**Comment by Gumbobrot** [comment]
> > ![image](https://user-images.githubusercontent.com/110686855/196422440-1c054e5c-7f3d-4b0b-8758-46bc2c45acfd.png) C:\Users\dehme\Desktop\Hazard-Token-Grabber-v3-main>pyinstaller hazard-v3.py --onefile 'pyinstaller' is not recognized as an internal command or external, an executable program or a batch file.
> > 
> > everything works except that the 'tutorial' to compile an exe does not work for me
> 
> You need to install pyinstaller using pip. Try "pip3 install pyinstaller"

Yeah, I know, that's why I told him to run the builder. It automatically installs all the requirements. I added pyinstaller to it, but normally it's already built-in to Python.
