### ISSUE TITLE
im not sure i can trust this source

### ISSUE THREAD

**Issue by Queveryyy** [schwungvoll/Hazard-Token-Grabber-v3#3]
it might be dangerous

**Comment by schwungvoll** [comment]
fucking dumb nigga shut up it's open source if you don't trust join cheataway server and download your shit before accusing others :)

**Comment by zappelig** [comment]
Dude it is open source. Get a brain, learn coding and read the stuff by yourself if the program is open source. And normally that it gets detected or anything. It collects d@t@ and sends it through a Di$c0rd Webhook.
